### PR TITLE
Exclude the data of CLB from the producer

### PR DESCRIPTION
**Pull request by lagartoverde**
OP-2982

### CODE REVIEW

**Review by mirdono — COMMENTED** [review]
Looks good to me, not an expert on producers though.

**Review by aliokan — COMMENTED** [review]
**Question:** Is only CLB use that producer?

**Comment by lagartoverde** [comment]
> **Question:** Is only CLB use that producer?
Yes

**Comment by lagartoverde** [comment]
Can I merge this then?

**Review by aliokan — APPROVED** [review]
:+1:

**Pull request merged**
