### PR TITLE
remove dummy worship service

### PR DESCRIPTION
**Pull request by iurianu**
OP-2125

### CODE REVIEW

**Review by claire-lovisa — COMMENTED** [review]
Did the curl call work for you ? Doesn't seem to do its job when I try it

**Comment by iurianu** [comment]
> Did the curl call work for you ? Doesn't seem to do its job when I try it

**Comment by claire-lovisa** [comment]
It still doesn't work for me. Could some else take a look ? (cc @bdevloed haha)
I've been also trying to use the new migrations version here https://github.com/lblod/app-organization-portal/pull/235 and it seemed to work, and in there no need for curl calls, so we could also go with that option

**Comment by claire-lovisa** [comment]
Closing, I'll merge #235 which contains the fix of this PR

**Pull request closed without merging**
