### PR TITLE
bugfix non utf8 characters

### PR DESCRIPTION
**Pull request by nbittich**
OP-2044 && OP-1915

would be nice to have it for 1.14

### CODE REVIEW

**Review by claire-lovisa — APPROVED** [review]
Do you also have a curl call, to update QA's index without having to reindex it ?
No problem to ship it with 1.14, you can merge directly to master then, I have a frontend fix to do as well, i'll deploy both at the same time on QA, then prod when it's all ok :)

**Review by bdevloed — APPROVED** [review]
Looks good to me. I guess what's still pending - in other prs - is to:
- find the root cause
- verify all strings, not just `André`?

**Comment by nbittich** [comment]
> Looks good to me. I guess what's still pending - in other prs - is to:
> 
>     * find the root cause
> 
>     * verify all strings, not just `André`?

I verified all ?o with type xsd:string  (added csv file under OP-1915 the git sparql.csv)

seems that's all we have. iconv gives 0 as an output.

**Comment by nbittich** [comment]
> Do you also have a curl call, to update QA's index without having to reindex it ? No problem to ship it with 1.14, you can merge directly to master then, I have a frontend fix to do as well, i'll deploy both at the same time on QA, then prod when it's all ok :)

I've added the curl calls

**Pull request merged**
